name: inception
version: "3.5"

volumes:
        mariadb:
            name: mariadb
            driver: local
            driver_opts:
                  device: /home/gsapio/data/mariadb
                  o: bind
                  type: none


networks:
    mynet:
        name: mynet


services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - mynet
        restart: always

        