name: inception
version: "3.5"

volumes:
        mariadb:
            name: mariadb
            driver: local
            driver_opts:
                  device: /home/gsapio/data/mariadb
                  o: bind
                  type: none
        wordpress:
            name: wordpress
            driver: local 
            driver_opts:
                    device: /home/gsapio/data/wordpress
                    o: bind
                    type: none

networks:
    mynet:
        name: mynet


services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - mynet
        restart: always
        ports: 
          - 3030:3306
        deploy:
          resources:
            limits:
              memory: 1G
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        depends_on:
          - mariadb
        volumes:
          - wordpress:/var/www/html
        env_file:
          - .env
        networks:
          - mynet
        restart: always

